python src/main.py  --seed 1 \
                    --n 10000 \
                    --d 88 \
                    --graph_type ER \
                    --degree 4 \
                    --noise_type gaussian_ev \
                    --equal_variances \
                    --lambda_1 2e-2 \
                    --lambda_2 5.0 \
                    --checkpoint_iter 5000 \
                    --training_path /dataset/Bayesian_Data/FORMED_NOISY/FORMED_DATA_I10/trainingData_FORMED_I10_10k.csv \
                    --gt_path /dataset/Bayesian_Data/FORMED/DAGtrue_FORMED_bi.csv 